/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.xavier.csci;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting",
                classUnderTest.getGreeting(""));

    }

    @Test public void testThatYouCanPassNothingIn() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting",
                classUnderTest.getGreeting(""));

        assertEquals("Hello", classUnderTest.getGreeting(""));
    }
    @Test public void testThatYouCanPassASingleValue() {
        App classUnderTest = new App();


        assertEquals("This should have had Dan at the end of the string",
                "Hello Dan", classUnderTest.getGreeting("Dan"));
    }
}
