/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.xavier.csci;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class GreetingUtilTest {
    GreetingUtil classUnderTest;

    @Before
    public void setup() {
        classUnderTest = new GreetingUtil();
    }

    @Test public void testAppHasAGreeting() {

        assertNotNull("app should have a greeting",
                classUnderTest.getGreeting(""));

    }

    @Test public void testThatYouCanPassNothingIn() {
        assertNotNull("app should have a greeting",
                classUnderTest.getGreeting(""));

        assertEquals("Hello", classUnderTest.getGreeting(""));
    }
    @Test public void testThatYouCanPassASingleValue() {

        assertEquals("This should have had Dan at the end of the string",
                "Hello Dan", classUnderTest.getGreeting("Dan"));
    }
}
